modelVersion: 'v2'
pipelineId: dbt-pipeline
description: Run dbt pipeline for weather data.
runner: 'airflow'
owner: 'data-eng-team'
tags:
  - "job:datacloud:antigravity"
defaults:
  projectId: {{ project }}
  location: {{ region }}
  executionConfig:
    retries: 1

triggers:
  - schedule:
      interval: '0 2 * * *'
      startTime: '2025-11-01T00:00:00'
      endTime: '2026-12-01T00:00:00'
      catchup: false
      timezone: 'UTC'

actions:
  - pipeline:
      name: run_weather_dbt
      framework:
        dbt:
          airflowWorker:
            projectDirectoryPath: weather_dbt
